// Created by Jack
// Start Date: December 1st 2015
// This is the class responsible for the facilities within the program

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimSpace_JAT
{
    class Facility
    {
        // The cost to build each facility
        protected int _cost;
        // The cost of maintaining each facility (cost of keeping it every month) 
        protected int _maintenance;
        // The amount of power required to build each facility
        protected int _power;
        // The amount of money generated each month from the facility
        protected int _revenue;
        // The amount of pollution generated by the facility each month that would result in an unhappy community the more and more pollution is created
        protected int _pollution;

        /// <summary>
        /// Using the public integer of Cost, get and set the protected integer of Cost
        /// </summary>
        public int Cost
        {
            get
            {
                return _cost;
            }
            protected set
            {
                _cost = value;
            }
         }

        /// <summary>
        /// Using the public integer of Maintenance, get and set the protected integer of Maintenance
        /// </summary>
        public int Maintenance
        {
            get
            {
                return _maintenance;
            }
            protected set
            {
                _maintenance = value;
            }
        }

        /// <summary>
        /// Using the public integer of Power, get and set the protected integer of Power
        /// </summary>
        public int Power
        {
            get
            {
                return _power;
            }
            protected set
            {
                _power = value;
            }
        }

        /// <summary>
        /// Using the public integer of Revenue, get and set the protected integer of Revenue
        /// </summary>
        public int Revenue
        {
            get
            {
                return _revenue;
            }
            protected set
            {
                _revenue = value;
            }
        }

        /// <summary>
        /// Using the public integer of Pollution, get and set the protected integer of Pollution
        /// </summary>
        public int Pollution
        {
            get
            {
                return _pollution;
            }
            protected set
            {
                _pollution = value;
            }
        }
    }
}
